[tactic] outline
EasyCrypt/easycrypt pull request #473
Opened 2023-11-29 12:57 UTC by Cameron-Low

The main idea is to provide an inverse to `inline` when proving an equiv.

Currently, it supports basic procedure unification that requires manual selection of the program slice to unify with, as well as, requiring near exact matches on program structure. An optional return value can be supplied for situations where the return expression is just a program variable and needs to be renamed/deconstructed.
 
There is also support for statement outlining although, this is more of a `transitivity *` with program slicing so may require change. 

Syntax and variants: 
- Procedure outlining: `outline {m} [s - e] M.foo` or `outline {m} [s - e] M.foo @ lv`
- Statement outlining: `outline {m} [s - e] { s1; s2; ... }`

_m_: 1 or 2
_s_,_e_: code position
_M.foo_: path to procedure
_lv_: a left-value

when _s_ = _e_, one can use `[s]` instead of `[s-s]`

For example usage see: _examples/tactics/outline.ec_

2023-12-01 18:04 UTC, fdupress commented
To note, this is part of the re-engineering of `rewrite equiv` into separate code matching and contextual call rewriting (as per discussions on the old PR).

Providing smarter code matching could help in reduction steps. Providing better contextual call rewriting could help in Hoare goals. (Where we rewrite a procedure call into another procedure on which we may already have a useful lemma.)

2023-12-01 20:52 UTC, Cameron-Low commented
Without playing shift/reduce whack-a-mole, I can get `outline {m} [s - e] lv <@ M.foo` but for the non LV variant it would need to be something like `outline {m} [s - e] _ <@ M.foo`.

2023-12-12 09:18 UTC, strub requested changes
I left 2 comments. Otherwise, LGTM.

2023-12-12 09:18 UTC, strub commented on examples/tactics/outline.ec
Now that we have unit tests in main, could you move this file to the unit test directory?

2023-12-12 09:18 UTC, strub commented on src/phl/ecPhlOutline.ml
> +(*---------------------------------------------------------------------------------------*)
Does this unification procedure is general enough to be factored out of this file?

2023-12-12 09:21 UTC, strub commented
Also, your PR description should be in the commit description.

2023-12-13 15:05 UTC, Cameron-Low commented
@strub, the most recent commit should address all the comments you had.

2023-12-13 15:25 UTC, strub approved these changes

2023-12-14 13:09 UTC, Cameron-Low commented
Most recent push was just an amendment to the commit message. Otherwise shall I merge this?

2023-12-15 09:36 UTC, fdupress commented
It's approved: merge and add doc to the wiki.

2023-12-15 10:45 UTC, merged